export const pageTitles = {
    '/': 'Головна',
    '/delivery-and-return': 'Доставка і повернення',
    '/about': 'Про нас',
    '/payment-methods': 'Оплата',
    '/contract-offer': 'Договір-оферта',
    '/contacts': 'Контакти',
    '/wishlist': 'Пакунок малюка',
    '/cart': 'Мій кошик',
    '/checkout': 'Оформлення замовлення',
    "/admin": "Панель адміністратора",
    "/admin/comments": "Панель адміністратора",
    "/admin/products": "Панель адміністратора",
    "/admin/orders": "Панель адміністратора",
}